# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 01:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('priority_level', models.PositiveSmallIntegerField()),
                ('day', models.CharField(max_length=10)),
                ('us_gov', models.BooleanField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 5, 15, 1, 41, 14, 468463, tzinfo=utc))),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('clear_level', models.CharField(choices=[('UC', 'UNCLASSIFIED'), ('CF', 'CONFIDENTIAL'), ('S', 'SECRET'), ('TS', 'TOP_SECRET')], default='TS', max_length=2)),
                ('citizenship', models.CharField(choices=[('USA', 'United States'), ('GBR', 'Great Britian'), ('CAN', 'Canada'), ('AUS', 'Australia'), ('NZL', 'New Zealand')], default='USA', max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
