# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_auto_20170515_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
