# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_auto_20170515_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
